export const gameData ={
    players:{
        player1:{
            playerTurn: false,
            playerColor: "white",
            chessPieces:[
                {
                   id:"",
                   type:"king",
                   position:[4,1]
                   
                },
                {
                   id:"",
                   type:"queen",
                   position:[5,1]
                },
                {
                   id:"",
                   type:"bishop",
                   position:[6,1]
                },
                {
                   id:"",
                   type:"bishop",
                   position:[3,1]
                },
                {
                   id:"",
                   type:"knight",
                   position:[2,1]
                },
                {
                   id:"",
                   type:"knight",
                   position:[7,1]
                },
                {
                   id:"",
                   type:"rook",
                   position:[1,1]
                },
                {
                   id:"",
                   type:"rook",
                   position:[8,1]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[1,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[2,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[3,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[4,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[5,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[6,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[7,2]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[8,2]
                },
            ]
        },
        player2:{
            playerTurn: false,
            playerColor: "black",
            chessPieces:[
                {
                   id:"",
                   type:"king",
                   position:[5,8]
                },
                {
                   id:"",
                   type:"queen",
                   position:[4,8]
                },
                {
                   id:"",
                   type:"bishop",
                   position:[6,8]
                },
                {
                   id:"",
                   type:"bishop",
                   position:[3,8]
                },
                {
                   id:"",
                   type:"knight",
                   position:[2,8]
                },
                {
                   id:"",
                   type:"knight",
                   position:[7,8]
                },
                {
                   id:"",
                   type:"rook",
                   position:[1,8]
                },
                {
                   id:"",
                   type:"rook",
                   position:[8,8]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[1,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[2,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[3,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[4,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[5,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[6,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[7,7]
                },
                {
                   id:"",
                   type:"pawn",
                   position:[8,7]
                },
            ]
        }
    },
}